# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=releasewithsymbols_x86
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

RESCOMP = windres
INCLUDES += -I../../../source -isystem ../../../external/gmod-module-base/include -isystem ../../../external/luajit -isystem ../../../external/metamod-source/core/sourcehook -isystem ../../../external/garrysmod_common-x86-64/include -isystem ../../../external/garrysmod_common-x86-64/helpers/include -isystem ../../../external/garrysmod_common-x86-64/helpers_extended/include -isystem ../../../external/garrysmod_common-x86-64/sourcesdk-minimal/common -isystem ../../../external/garrysmod_common-x86-64/sourcesdk-minimal/game/shared -isystem ../../../external/garrysmod_common-x86-64/sourcesdk-minimal/public -isystem ../../../external/garrysmod_common-x86-64/sourcesdk-minimal/game/server -isystem ../../../external/garrysmod_common-x86-64/sourcesdk-minimal/public/tier0 -isystem ../../../external/garrysmod_common-x86-64/sourcesdk-minimal/public/tier1
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),releasewithsymbols_x86_64)
TARGETDIR = x86_64/ReleaseWithSymbols
TARGET = $(TARGETDIR)/gmsv_turbostroi_linux64.dll
OBJDIR = x86_64/ReleaseWithSymbols/intermediate/gmsv_turbostroi
DEFINES += -DGMOD_ALLOW_OLD_TYPES -DGMOD_ALLOW_LIGHTUSERDATA -DNDEBUG -DGMMODULE -DTURBOSTROI_SERVER -DIS_SERVERSIDE=true -DGAME_DLL -DGMOD_USE_SOURCESDK -DRAD_TELEMETRY_DISABLED -DNO_STRING_T -DVECTOR -DVERSION_SAFE_STEAM_API_INTERFACES -DPROTECTED_THINGS_ENABLE -D_DLL_EXT=.so -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DSWDS -DPLATFORM_64BITS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -Og -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -Og -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes
LIBS += ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libhelpers_extended.a ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libhelpers.a ../../../external/garrysmod_common-x86-64/sourcesdk-minimal/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libtier1.a -llua51 -ltier0 -lvstdlib
LDDEPS += ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libhelpers_extended.a ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libhelpers.a ../../../external/garrysmod_common-x86-64/sourcesdk-minimal/projects/linux/gmake2/x86_64/ReleaseWithSymbols/libtier1.a
ALL_LDFLAGS += $(LDFLAGS) -L../../../external/garrysmod_common-x86-64/sourcesdk-minimal/lib/public/linux64 -L/usr/lib64 -m64 -shared -Wl,-soname=gmsv_turbostroi_linux64.dll

else ifeq ($(config),releasewithsymbols_x86)
TARGETDIR = x86/ReleaseWithSymbols
TARGET = $(TARGETDIR)/gmsv_turbostroi_linux.dll
OBJDIR = x86/ReleaseWithSymbols/intermediate/gmsv_turbostroi
DEFINES += -DGMOD_ALLOW_OLD_TYPES -DGMOD_ALLOW_LIGHTUSERDATA -DNDEBUG -DGMMODULE -DTURBOSTROI_SERVER -DIS_SERVERSIDE=true -DGAME_DLL -DGMOD_USE_SOURCESDK -DRAD_TELEMETRY_DISABLED -DNO_STRING_T -DVECTOR -DVERSION_SAFE_STEAM_API_INTERFACES -DPROTECTED_THINGS_ENABLE -D_DLL_EXT=.so -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DSWDS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -Og -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -Og -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes
LIBS += ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86/ReleaseWithSymbols/libhelpers_extended.a ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86/ReleaseWithSymbols/libhelpers.a ../../../external/garrysmod_common-x86-64/sourcesdk-minimal/projects/linux/gmake2/x86/ReleaseWithSymbols/libtier1.a -llua51 -ltier0 -lvstdlib
LDDEPS += ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86/ReleaseWithSymbols/libhelpers_extended.a ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86/ReleaseWithSymbols/libhelpers.a ../../../external/garrysmod_common-x86-64/sourcesdk-minimal/projects/linux/gmake2/x86/ReleaseWithSymbols/libtier1.a
ALL_LDFLAGS += $(LDFLAGS) -L../../../external/luajit/linux32 -L../../../external/garrysmod_common-x86-64/sourcesdk-minimal/lib/public/linux32 -L/usr/lib32 -m32 -shared -Wl,-soname=gmsv_turbostroi_linux.dll

else ifeq ($(config),release_x86_64)
TARGETDIR = x86_64/Release
TARGET = $(TARGETDIR)/gmsv_turbostroi_linux64.dll
OBJDIR = x86_64/Release/intermediate/gmsv_turbostroi
DEFINES += -DGMOD_ALLOW_OLD_TYPES -DGMOD_ALLOW_LIGHTUSERDATA -DNDEBUG -DGMMODULE -DTURBOSTROI_SERVER -DIS_SERVERSIDE=true -DGAME_DLL -DGMOD_USE_SOURCESDK -DRAD_TELEMETRY_DISABLED -DNO_STRING_T -DVECTOR -DVERSION_SAFE_STEAM_API_INTERFACES -DPROTECTED_THINGS_ENABLE -D_DLL_EXT=.so -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DSWDS -DPLATFORM_64BITS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -flto -O3 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -flto -O3 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes
LIBS += ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86_64/Release/libhelpers_extended.a ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86_64/Release/libhelpers.a ../../../external/garrysmod_common-x86-64/sourcesdk-minimal/projects/linux/gmake2/x86_64/Release/libtier1.a -llua51 -ltier0 -lvstdlib
LDDEPS += ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86_64/Release/libhelpers_extended.a ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86_64/Release/libhelpers.a ../../../external/garrysmod_common-x86-64/sourcesdk-minimal/projects/linux/gmake2/x86_64/Release/libtier1.a
ALL_LDFLAGS += $(LDFLAGS) -L../../../external/garrysmod_common-x86-64/sourcesdk-minimal/lib/public/linux64 -L/usr/lib64 -m64 -flto -shared -Wl,-soname=gmsv_turbostroi_linux64.dll

else ifeq ($(config),release_x86)
TARGETDIR = x86/Release
TARGET = $(TARGETDIR)/gmsv_turbostroi_linux.dll
OBJDIR = x86/Release/intermediate/gmsv_turbostroi
DEFINES += -DGMOD_ALLOW_OLD_TYPES -DGMOD_ALLOW_LIGHTUSERDATA -DNDEBUG -DGMMODULE -DTURBOSTROI_SERVER -DIS_SERVERSIDE=true -DGAME_DLL -DGMOD_USE_SOURCESDK -DRAD_TELEMETRY_DISABLED -DNO_STRING_T -DVECTOR -DVERSION_SAFE_STEAM_API_INTERFACES -DPROTECTED_THINGS_ENABLE -D_DLL_EXT=.so -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DSWDS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -flto -O3 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -flto -O3 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes
LIBS += ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86/Release/libhelpers_extended.a ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86/Release/libhelpers.a ../../../external/garrysmod_common-x86-64/sourcesdk-minimal/projects/linux/gmake2/x86/Release/libtier1.a -llua51 -ltier0 -lvstdlib
LDDEPS += ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86/Release/libhelpers_extended.a ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86/Release/libhelpers.a ../../../external/garrysmod_common-x86-64/sourcesdk-minimal/projects/linux/gmake2/x86/Release/libtier1.a
ALL_LDFLAGS += $(LDFLAGS) -L../../../external/luajit/linux32 -L../../../external/garrysmod_common-x86-64/sourcesdk-minimal/lib/public/linux32 -L/usr/lib32 -m32 -flto -shared -Wl,-soname=gmsv_turbostroi_linux.dll

else ifeq ($(config),debug_x86_64)
TARGETDIR = x86_64/Debug
TARGET = $(TARGETDIR)/gmsv_turbostroi_linux64.dll
OBJDIR = x86_64/Debug/intermediate/gmsv_turbostroi
DEFINES += -DGMOD_ALLOW_OLD_TYPES -DGMOD_ALLOW_LIGHTUSERDATA -DDEBUG -D_DEBUG -DGMMODULE -DTURBOSTROI_SERVER -DIS_SERVERSIDE=true -DGAME_DLL -DGMOD_USE_SOURCESDK -DRAD_TELEMETRY_DISABLED -DNO_STRING_T -DVECTOR -DVERSION_SAFE_STEAM_API_INTERFACES -DPROTECTED_THINGS_ENABLE -D_DLL_EXT=.so -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DSWDS -DPLATFORM_64BITS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -O0 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -O0 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes
LIBS += ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86_64/Debug/libhelpers_extended.a ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86_64/Debug/libhelpers.a ../../../external/garrysmod_common-x86-64/sourcesdk-minimal/projects/linux/gmake2/x86_64/Debug/libtier1.a -llua51 -ltier0 -lvstdlib
LDDEPS += ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86_64/Debug/libhelpers_extended.a ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86_64/Debug/libhelpers.a ../../../external/garrysmod_common-x86-64/sourcesdk-minimal/projects/linux/gmake2/x86_64/Debug/libtier1.a
ALL_LDFLAGS += $(LDFLAGS) -L../../../external/garrysmod_common-x86-64/sourcesdk-minimal/lib/public/linux64 -L/usr/lib64 -m64 -shared -Wl,-soname=gmsv_turbostroi_linux64.dll

else ifeq ($(config),debug_x86)
TARGETDIR = x86/Debug
TARGET = $(TARGETDIR)/gmsv_turbostroi_linux.dll
OBJDIR = x86/Debug/intermediate/gmsv_turbostroi
DEFINES += -DGMOD_ALLOW_OLD_TYPES -DGMOD_ALLOW_LIGHTUSERDATA -DDEBUG -D_DEBUG -DGMMODULE -DTURBOSTROI_SERVER -DIS_SERVERSIDE=true -DGAME_DLL -DGMOD_USE_SOURCESDK -DRAD_TELEMETRY_DISABLED -DNO_STRING_T -DVECTOR -DVERSION_SAFE_STEAM_API_INTERFACES -DPROTECTED_THINGS_ENABLE -D_DLL_EXT=.so -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DSWDS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -O0 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -O0 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes
LIBS += ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86/Debug/libhelpers_extended.a ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86/Debug/libhelpers.a ../../../external/garrysmod_common-x86-64/sourcesdk-minimal/projects/linux/gmake2/x86/Debug/libtier1.a -llua51 -ltier0 -lvstdlib
LDDEPS += ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86/Debug/libhelpers_extended.a ../../../external/garrysmod_common-x86-64/projects/linux/gmake2/x86/Debug/libhelpers.a ../../../external/garrysmod_common-x86-64/sourcesdk-minimal/projects/linux/gmake2/x86/Debug/libtier1.a
ALL_LDFLAGS += $(LDFLAGS) -L../../../external/luajit/linux32 -L../../../external/garrysmod_common-x86-64/sourcesdk-minimal/lib/public/linux32 -L/usr/lib32 -m32 -shared -Wl,-soname=gmsv_turbostroi_linux.dll

endif

# Per File Configurations
# #############################################

PERFILE_FLAGS_0 = $(ALL_CXXFLAGS) -Wno-invalid-offsetof

# File sets
# #############################################

CUSTOM :=
GENERATED :=
OBJECTS :=

CUSTOM += $(OBJDIR)/gmsv_turbostroi_win32.res
GENERATED += $(OBJDIR)/gmsv_turbostroi_win32.o
GENERATED += $(OBJDIR)/gmsv_turbostroi_win32.res
GENERATED += $(OBJDIR)/interfaces.o
GENERATED += $(OBJDIR)/sourcehook.o
GENERATED += $(OBJDIR)/sourcehook_hookmangen.o
GENERATED += $(OBJDIR)/sourcehook_impl_chookidman.o
GENERATED += $(OBJDIR)/sourcehook_impl_chookmaninfo.o
GENERATED += $(OBJDIR)/sourcehook_impl_cproto.o
GENERATED += $(OBJDIR)/sourcehook_impl_cvfnptr.o
OBJECTS += $(OBJDIR)/gmsv_turbostroi_win32.o
OBJECTS += $(OBJDIR)/interfaces.o
OBJECTS += $(OBJDIR)/sourcehook.o
OBJECTS += $(OBJDIR)/sourcehook_hookmangen.o
OBJECTS += $(OBJDIR)/sourcehook_impl_chookidman.o
OBJECTS += $(OBJDIR)/sourcehook_impl_chookmaninfo.o
OBJECTS += $(OBJDIR)/sourcehook_impl_cproto.o
OBJECTS += $(OBJDIR)/sourcehook_impl_cvfnptr.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(CUSTOM) $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking gmsv_turbostroi
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning gmsv_turbostroi
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) rmdir /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

$(CUSTOM): | prebuild
ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/interfaces.o: ../../../external/garrysmod_common-x86-64/sourcesdk-minimal/interfaces/interfaces.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sourcehook.o: ../../../external/metamod-source/core/sourcehook/sourcehook.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sourcehook_hookmangen.o: ../../../external/metamod-source/core/sourcehook/sourcehook_hookmangen.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sourcehook_impl_chookidman.o: ../../../external/metamod-source/core/sourcehook/sourcehook_impl_chookidman.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sourcehook_impl_chookmaninfo.o: ../../../external/metamod-source/core/sourcehook/sourcehook_impl_chookmaninfo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sourcehook_impl_cproto.o: ../../../external/metamod-source/core/sourcehook/sourcehook_impl_cproto.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sourcehook_impl_cvfnptr.o: ../../../external/metamod-source/core/sourcehook/sourcehook_impl_cvfnptr.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/gmsv_turbostroi_win32.res: ../../../source/gmsv_turbostroi_win32.rc
	@echo $(notdir $<)
	$(SILENT) $(RESCOMP) $< -O coff -o "$@" $(ALL_RESFLAGS)
$(OBJDIR)/gmsv_turbostroi_win32.o: ../../../source/gmsv_turbostroi_win32.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif